config/routes.rb
SemiDndFileManager::Application.routes.draw do
  resources :file_containers

end

app/models/file_container.rb
class FileContainer < ActiveRecord::Base
  attr_accessible :description, :name, :s3_file, :page

  has_attached_file :s3_file, :path => "/files/:id/:extension", :url => ":s3_domain_url"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/file_containers_controller.rb
class FileContainersController < ApplicationController
  # GET /file_containers
  # GET /file_containers.json
  def index
    @page = params[:page]

    if params[:page].nil?
      @file_containers = FileContainer.all
    else
      @file_containers = FileContainer.where(:page => params[:page] )
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @file_containers }
    end
  end

  # GET /file_containers/1
  # GET /file_containers/1.json
  def show
    @file_container = FileContainer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @file_container }
    end
  end

  # GET /file_containers/new
  # GET /file_containers/new.json
  def new

    @file_container = FileContainer.new
    @file_container.page = params[:page]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @file_container }
    end
  end

  # GET /file_containers/1/edit
  def edit
    @file_container = FileContainer.find(params[:id])
  end

  # POST /file_containers
  # POST /file_containers.json
  def create
    @file_container = FileContainer.new(params[:file_container])

    respond_to do |format|
      if @file_container.save
        format.html { redirect_to file_containers_url, notice: 'File was successfully uploaded.' }
        format.json { render json: @file_container, status: :created, location: @file_container }
      else
        format.html { render action: "new" }
        format.json { render json: @file_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /file_containers/1
  # PUT /file_containers/1.json
  def update
    @file_container = FileContainer.find(params[:id])

    respond_to do |format|
      if @file_container.update_attributes(params[:file_container])
        format.html { redirect_to file_containers_url, notice: 'File was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @file_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_containers/1
  # DELETE /file_containers/1.json
  def destroy
    @file_container = FileContainer.find(params[:id])
    @file_container.destroy

    respond_to do |format|
      format.html { redirect_to file_containers_url, notice: 'File was deleted updated.'  }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_containers_helper.rb
module FileContainersHelper
end

app/views/file_containers/_form.html.erb
<%= form_for(@file_container) do |f| %>
  <% if @file_container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_container.errors.count, "error") %> prohibited this file_container from being saved:</h2>

      <ul>
      <% @file_container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

    <div class="field">
      <%= f.label :s3_file %><br />
      <%= f.file_field :s3_file %>
    </div>

    <div class="field">
      <%= f.label :page %><br />
      <%= f.text_field :page %>
    </div>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_containers/edit.html.erb
<h1>Editing file_container</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_container %> |
<%= link_to 'Back', file_containers_path %>

app/views/file_containers/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @page %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Download</th>
    <th>Delete</th>
  </tr>

<% @file_containers.each do |file_container| %>
  <tr>
    <td><%= file_container.name %></td>
    <td><%= file_container.description %></td>
    <td><%= link_to "Download",file_container.s3_file.url(:original, false) %></td>
    <td><%= link_to 'Delete', file_container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Upload File', new_file_container_path(page: @page) %>

app/views/file_containers/new.html.erb
<h1>New file_container</h1>

<%= render 'form' %>

<%= link_to 'Back', file_containers_path %>

app/views/file_containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @file_container.name %>
</p>

<p>
  <b>Description:</b>
  <%= @file_container.description %>
</p>


<%= link_to 'Edit', edit_file_container_path(@file_container) %> |
<%= link_to 'Back', file_containers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SemiDndFileManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>